### ISSUE TITLE
1e crashes with java.lang.NumberFormatException: For input string: ""

### ISSUE THREAD

**Issue by vanniktech** [uklimaschewski/EvalEx#190]
I'd expect `1e` to print `2.71828182846` instead I'm getting an exception:

```
java.lang.NumberFormatException: For input string: ""
    at java.lang.Integer.parseInt(Integer.java:627)
    at java.lang.Integer.parseInt(Integer.java:650)
    at java.math.BigDecimal.<init>(BigDecimal.java:336)
    at java.math.BigDecimal.<init>(BigDecimal.java:444)
    at com.udojava.evalex.Expression$59.eval(Expression.java:1363)
    at com.udojava.evalex.Expression.eval(Expression.java:1398)
    at com.udojava.evalex.Expression.eval(Expression.java:1273)
```

**Comment by RobertZenz** [comment]
There is no implicit multiplication, you have to specify a multiplication. See #64.

**Comment by vanniktech** [comment]
My problem is similar to the one from @FlashTek. The input is coming from a user and he'd expect it to be multiplied.

> E.g. What about A5BSIN(2) - is this a function named A5BSIN or an expression A*5*SIN(2) ?

If a function with a name `A5BSIN` is defined then it should take precedence. Otherwise `A*5*SIN(2)` as long as `A` can be satisfied. If none can then it can crash.

**Comment by vanniktech** [comment]
The same should be applied for `1π` where PI is defined as `.setVariable("π", Expression.PI)`.
