### ISSUE TITLE
NumberFormatException for ISO dates as a variable value

### ISSUE THREAD

**Issue by chkal** [uklimaschewski/EvalEx#319]
If you have code like this:

```java
new Expression( "23" )
  .with( "someString", "2022-01-02" )
  .eval();
```

The following exception is thrown:

```
java.lang.NumberFormatException
	at java.math.BigDecimal.<init>(BigDecimal.java:497)
	at java.math.BigDecimal.<init>(BigDecimal.java:827)
	at com.udojava.evalex.Expression.setVariable(Expression.java:1804)
	at com.udojava.evalex.Expression.with(Expression.java:1923)
	at com.udojava.evalex.TestVariables.testIsoDateInString(TestVariables.java:119)
```

The issue seems to be that `Expression.isNumber()` returns `true` and creating a `BigDecimal` from the string fails.

Please note that this issue occurs on the current `2.x` branch.

**Comment by chkal** [comment]
I just created a PR for a unit test that reproduces this issue: https://github.com/ezylang/EvalEx/pull/320
